version: '3.8'
services:
    # GATEWAY
    gateway:
        build:
            context: .
            dockerfile: ./apps/gateway/Dockerfile
        ports:
            - '3000:3000'
        depends_on:
            - auth
            - event

    # AUTH SERVICE
    auth:
        build:
            context: .
            dockerfile: ./apps/auth/Dockerfile
        expose:
            - '3001'
        env_file:
            - ./apps/auth/.env
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on:
            - auth-mongo
            - redis

    auth-mongo:
        image: mongo
        container_name: auth-mongo
        ports:
            - '27017:27017'
        volumes:
            - auth_data:/data/db

    # EVENT SERVICE
    event:
        build:
            context: .
            dockerfile: ./apps/event/Dockerfile
        expose:
            - '3002'
        env_file:
            - ./apps/event/.env
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on:
            - event-mongo
            - redis

    event-mongo:
        image: mongo
        container_name: event-mongo
        ports:
            - '27018:27017'
        volumes:
            - event_data:/data/db

    redis:
        image: redis:6.2
        container_name: redis
        ports:
            - '6379:6379'

volumes:
    auth_data:
    event_data:
